const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',      
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    SORT_ASCENDING: 'SORT_ASCENDING',
    SORT_DESCENDING: 'SORT_DESCENDING',
}

export default ShopActionTypes;